import type { AnalysisResult } from '../types';

export function exportJSON(result: AnalysisResult): string {
  return JSON.stringify(result, null, 2);
}

export function exportMarkdown(result: AnalysisResult): string {
  const { inferred, signals, inputPreview, mode, timestamp } = result;
  const date = new Date(timestamp).toISOString();
  const sigLines = signals
    .map(
      (s) =>
        `- **[${s.category}] ${s.label}** — ${s.detail} _(confidence ${Math.round(s.confidence * 100)}%)_`
    )
    .join('\n');

  return `# NYTHIS Obsidian — Reverse Prompt Analysis

> Mode: \`${mode}\` · Generated: ${date}
> Aggregate confidence: **${Math.round(inferred.confidence * 100)}%**${inferred.modelHint ? `\n> Model hint: ${inferred.modelHint}` : ''}

## Input preview

\`\`\`
${inputPreview}
\`\`\`

## Inferred system prompt

\`\`\`
${inferred.systemPrompt}
\`\`\`

## Inferred user prompt

\`\`\`
${inferred.userPrompt}
\`\`\`

## Reusable template

\`\`\`
${inferred.reusableTemplate}
\`\`\`

## Signals detected (${signals.length})

${sigLines || '_No signals detected._'}

---
_Generated by [NYTHIS Obsidian Reverse Prompt](https://github.com/BIGSTODG/nythis-obsidian-reverse-prompt) — open source, no API keys, 100% client-side._
`;
}

export function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
